---
- name: Build and push Docker image to Docker Hub and deploy to Minikube
  hosts: 13.239.64.64  # You can use 'localhost' to run tasks locally
  become: yes
  tasks:
    - name: Copy target to the remote server
      copy:
        src: /home/ubuntu/target/  # Update the path to your Dockerfile
        dest: /home/ubuntu/  # Change this destination path as needed
      become_user: ubuntu

    - name: Build the Docker image
      command: docker build -t abc-techno:latest /home/ubuntu/
      become_user: ubuntu
      args:
        executable: /bin/bash

    - name: Tag the Docker image
      command: docker tag abc-techno:latest fairozb11/abc-techno:latest
      become_user: ubuntu
      args:
        executable: /bin/bash

    - name: Log in to Docker Hub
      command: docker login -u fairozb11 -p Davangere@77
      become_user: ubuntu
      args:
        executable: /bin/bash

    - name: Push the Docker image to Docker Hub
      command: docker push fairozb11/abc-techno:latest
      become_user: ubuntu
      args:
        executable: /bin/bash

    - name: Start a container
      community.docker.docker_container:
        name: abc-techno
        image: fairozb11/abc-techno:latest
        state: started
        ports:
          - "8080:8080"

    - name: Apply Kubernetes manifest
      command: kubectl apply -f /home/ubuntu/deployment.yml  # Update the path to your Kubernetes manifest
      args:
        executable: /bin/bash
      become_user: ubuntu
